StylesPath = styles
MinAlertLevel = suggestion

Packages = Google, Readability, proselint
Vocab = WebMapX

[*.md]
BasedOnStyles = Vale, Google, Readability, proselint, WebMapX

# Te veel ruis voor technische documentatie
Google.Headings = NO
Google.Parens = NO
Google.Contractions = NO
Google.EmDash = NO
Google.Colons = NO

# Wel nuttig, maar niet te streng
Readability.ColemanLiau = suggestion
Readability.FleschReadingEase = suggestion
Google.Passive = suggestion
Google.Semicolons = suggestion
Google.Acronyms = suggestion
Google.OxfordComma = suggestion

# Deze wil je behouden
Vale.Spelling = error

